# Generated by Django 5.0.7 on 2024-08-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='walletColor',
            new_name='Color',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='walletDesc',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='walletIcon',
            new_name='Icon',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='walletName',
            new_name='Name',
        ),
    ]
