# Generated by Django 5.0.7 on 2024-08-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wallet_app', '0002_rename_walletcolor_wallet_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Color',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='Name',
            new_name='name',
        ),
    ]
