# Generated by Django 5.0.7 on 2024-08-13 05:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('number', 'Number'), ('email', 'Email'), ('password', 'Password'), ('select', 'Select'), ('multiSelect', 'MultiSelect'), ('date', 'Date'), ('time', 'Time'), ('file', 'File')], max_length=255)),
                ('field_value', models.JSONField()),
                ('label', models.CharField(max_length=255)),
                ('label_value', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
