# Generated by Django 5.0.7 on 2024-08-09 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('notes', models.TextField()),
                ('category_type', models.CharField(choices=[('income', 'income'), ('expense', 'expense')], max_length=20)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='Wallet_app.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
