# Generated by Django 5.0.7 on 2024-08-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='category',
            name='income',
        ),
    ]
