# Generated by Django 5.0.7 on 2024-08-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category_app', '0002_remove_category_expense_remove_category_income'),
        ('CustomField_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='custom_fields',
            field=models.ManyToManyField(related_name='categories', to='CustomField_app.customfield'),
        ),
    ]
