# Generated by Django 5.0.7 on 2024-08-09 05:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('personalEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_no', models.CharField(max_length=15)),
                ('alternatePhone', models.CharField(blank=True, max_length=15, null=True)),
                ('profilePicture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otpExpire', models.DateTimeField(blank=True, null=True)),
                ('financialYear', models.CharField(blank=True, max_length=20, null=True)),
                ('isGoogleSignup', models.BooleanField(default=False)),
                ('googleCredential', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
