# Generated by Django 5.0.7 on 2024-08-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_app', '0001_initial'),
        ('Wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='Wallet_app.wallet'),
        ),
    ]
