# Generated by Django 5.0.7 on 2024-08-09 06:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Wallet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='client_avatar/')),
                ('notes', models.TextField()),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='Wallet_app.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
