# Generated by Django 5.0.7 on 2024-08-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_app', '0001_initial'),
        ('CustomField_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='custom_fields',
            field=models.ManyToManyField(related_name='clients', to='CustomField_app.customfield'),
        ),
    ]
